### Recuperar informacion del pokemon ditto
GET http://localhost:1234/pokemon/ditto

### Crear un nuevo pokemon
POST http://localhost:1234/pokemon
Content-Type: application/json

{
    "name": "pikachu",
    "type": "electric",
    "moves": [
        "transform",
        "thunderbolt"
    ]
}