### Recuperar todas las peliculas
GET http://localhost:1234/movies

### recuperar una pelicula por el id
GET http://localhost:1234/movies/1033280f-1292-11f0-a90a-51b8a6198b6d

### Recuperar todas las peliculas por un genero
GET http://localhost:1234/movies?genre=ActioN

### Crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "The Godfather",
  "year": 1972,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://pics.filmaffinity.com/El_padrino-993414333-large.jpg",
  "genre": ["Crime", "Drama"],
  "rate": 9.1
}

### Borrar una pelicula
DELETE http://localhost:1234/movies/c90fdd6d-1257-11f0-a633-f03431582ac9

### Actualizar mi pelicula
PATCH http://localhost:1234/movies/58476487-1292-11f0-a90a-51b8a6198b6d
Content-Type: application/json

{
  "title": "Pelicula actualizada",
  "year": 2022,
  "Director": "Jose Zuniga",
  "genre": [        "Action",
        "Adventure",
        "Crime",
        "Drama",
        "Romance",
        "Sci-Fi"
        ]
}

